import type { Metadata } from "next";
import "./global.css";
import Link from "next/link";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function PageRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className="bg-blue-600 text-white shadow-lg">
          <nav className="container mx-auto px-4 py-4 flex justify-between items-center">
            <h1 className="text-2xl font-bold">My App</h1>
            <ul className="flex space-x-6">
              <li>
                {/* <a href="/" className="hover:underline">
                  Home
                </a> */}
                <Link href="/" className="hover:underline">
                  Home
                </Link>
              </li>
              <li>
                {/* <a href="/about" className="hover:underline">
                  About
                </a> */}
                <Link href="/about" className="hover:underline">
                  About
                </Link>
              </li>
              <li>
                {/* <a href="/contact" className="hover:underline">
                  Contact
                </a> */}
                <Link href="/contact" className="hover:underline">
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </header>

        <main className="flex-1 container mx-auto px-4 py-8">{children}</main>

        <footer className="bg-gray-800 text-white mt-auto">
          <div className="container mx-auto px-4 py-8 text-center">
            <p>&copy; 2025 My App. All rights reserved.</p>
            <p className="text-sm mt-2 opacity-75">
              Built with Next.js & Tailwind CSS
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
